name: Test against pacman
on:
  pull_request:

jobs:
  build:
    name: Lint and test yippee
    runs-on: ubuntu-latest
    container:
      image: jguer/yippee-builder:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Lint
        env:
          GOFLAGS: -buildvcs=false -tags=next
        run: /app/bin/golangci-lint run ./...
      - name: Run Build and Tests
        run: make test
      - name: Run Integration Tests
        continue-on-error: true
        run: |
          useradd -m yippee &&
          chown -R yippee:yippee . &&
          cp -r ~/go/ /home/yippee/go/ &&
          chown -R yippee:yippee /home/yippee/go/ &&
          su yippee -c "make test-integration"
